# Form implementation generated from reading ui file 'mat_about.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_About_Dialog(object):
    def setupUi(self, About_Dialog):
        About_Dialog.setObjectName("About_Dialog")
        About_Dialog.resize(896, 519)
        font = QtGui.QFont()
        font.setKerning(True)
        About_Dialog.setFont(font)
        About_Dialog.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("mat_main_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        About_Dialog.setWindowIcon(icon)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(About_Dialog)
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtWidgets.QLabel(parent=About_Dialog)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("mat_main_icon.png"))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=About_Dialog)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=About_Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=About_Dialog)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(parent=About_Dialog)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(parent=About_Dialog)
        font = QtGui.QFont()
        font.setUnderline(True)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.label_5.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_5.setIndent(6)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.textBrowser = QtWidgets.QTextBrowser(parent=About_Dialog)
        self.textBrowser.setEnabled(True)
        self.textBrowser.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.textBrowser.setReadOnly(True)
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.pushButton_about = QtWidgets.QPushButton(parent=About_Dialog)
        self.pushButton_about.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_about.setStyleSheet("color: rgb(0, 85, 255);\n"
"text-decoration: underline;\n"
"font: 13pt \"Segoe UI\";\n"
"border: 0px;")
        self.pushButton_about.setFlat(False)
        self.pushButton_about.setObjectName("pushButton_about")
        self.horizontalLayout.addWidget(self.pushButton_about)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.pushButton_author = QtWidgets.QPushButton(parent=About_Dialog)
        self.pushButton_author.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_author.setStyleSheet("color: rgb(0, 85, 255);\n"
"text-decoration: underline;\n"
"font: 13pt \"Segoe UI\";\n"
"border: 0px;")
        self.pushButton_author.setFlat(False)
        self.pushButton_author.setObjectName("pushButton_author")
        self.horizontalLayout.addWidget(self.pushButton_author)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.pushButton_license = QtWidgets.QPushButton(parent=About_Dialog)
        self.pushButton_license.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_license.setStyleSheet("color: rgb(0, 85, 255);\n"
"text-decoration: underline;\n"
"font: 13pt \"Segoe UI\";\n"
"border: 0px;")
        self.pushButton_license.setFlat(False)
        self.pushButton_license.setObjectName("pushButton_license")
        self.horizontalLayout.addWidget(self.pushButton_license)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(About_Dialog)
        QtCore.QMetaObject.connectSlotsByName(About_Dialog)

    def retranslateUi(self, About_Dialog):
        _translate = QtCore.QCoreApplication.translate
        About_Dialog.setWindowTitle(_translate("About_Dialog", "About"))
        self.label.setText(_translate("About_Dialog", "MAT"))
        self.label_2.setText(_translate("About_Dialog", "1.0.0 (64bit)"))
        self.label_3.setText(_translate("About_Dialog", "MAT is a free and open source audio conversion software."))
        self.label_4.setText(_translate("About_Dialog", "Support the MAT Project"))
        self.label_5.setText(_translate("About_Dialog", "Get involved"))
        self.textBrowser.setHtml(_translate("About_Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:10.5pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_about.setText(_translate("About_Dialog", "About"))
        self.pushButton_author.setText(_translate("About_Dialog", "Authors"))
        self.pushButton_license.setText(_translate("About_Dialog", "License"))
